marks=[]
m1=input("enter the marks of english")
m2=input("enter the marks of maths ")
m3=input("enter the marks of bio")
m4=input("enter the marks of chemistry")
m5=input("enter the marks of science")
m6=input("enter the marks of Ip")
marks.append(m1)
marks.append(m2)
marks.append(m3)
marks.append(m4)
marks.append(m5)
marks.append(m6)
marks.sort()
print(marks)